### ISSUE TITLE
[PATCH] lua 5.2 support not complete

### ISSUE THREAD

**Issue by lkardos** [lkardos/test#242]
I am packaging rpm for Arch Linux and can't get the rpm package to compile with Lua 5.2.    Lua 5.2 support is announced for 4.11.0:  http://rpm.org/wiki/Releases/4.11.0    The patch is given by:  http://lists.rpm.org/pipermail/rpm-maint/2012-October/003241.html  [[BR]]http://lists.rpm.org/pipermail/rpm-maint/attachments/20121007/6a152904/attachment.obj    And added to the 4.11.x branch in ac959fed0082cb253d45c7a04866e8654e962442      Trying to compile with Lua 5.2.1 however_ I get this error:  {{{  /var/abs/local/_src/_suse/rpm-org/src/rpm-4.11.0.1/rpmio/.libs/librpmio.so: undefined reference to `luaL_typerror'  /var/abs/local/_src/_suse/rpm-org/src/rpm-4.11.0.1/rpmio/.libs/librpmio.so: undefined reference to `luaL_getn'  /var/abs/local/_src/_suse/rpm-org/src/rpm-4.11.0.1/rpmio/.libs/librpmio.so: undefined reference to `luaL_putchar'  collect2: error: ld returned 1 exit status  }}}    Compiled with  {{{  ./configure \                  --prefix=/usr  \                  --sysconfdir=/etc  \                  --localstatedir=/var \                  --enable-python \                  --with-external-db \                  --with-lua \                  CPPFLAGS="`pkg-config --cflags nss`" \                  PYTHON=python2  make -j 1  }}}  on Arch Linux.    The package was previously using lua 5.1. I just tried lua 5.2 now since it was announced as supported. lua 5.2 is the current "lua" on Arch Linux.

**Comment by lkardos** [comment]
_Imported from trac issue 865.  Created by JonnyJD on 2013-04-04T15:18:19, last modified: 2013-04-05T11:37:05_

**Comment by lkardos** [comment]
_Trac comment by JonnyJD on 2013-04-04 15:24:17:_

luaL_typerror and luaL_putchar are in luaext/lposix.c  [[BR]] and luaL_getn is found in rpmio/rpmlua.c.    On Arch Linux I have:  {{{  $ grep -r luaL_typerror /usr/include/l*  /usr/include/lua5.1/lauxlib.h:LUALIB_API int (luaL_typerror) (lua_State *L_ int narg_ const char *tname);  $ grep -r luaL_getn /usr/include/l*  /usr/include/lua5.1/lauxlib.h:LUALIB_API int (luaL_getn) (lua_State *L_ int t);  /usr/include/lua5.1/lauxlib.h:#define luaL_getn(L_i)          ((int)lua_objlen(L_ i))  $ grep -r luaL_putchar /usr/include/l*  /usr/include/lua5.1/lauxlib.h:#define luaL_putchar(B_c)	luaL_addchar(B_c)  }}}  in contrast to for example:  {{{  $ grep -r luaL_checkstack /usr/include/l*  /usr/include/lauxlib.h:LUALIB_API void (luaL_checkstack) (lua_State *L_ int sz_ const char *msg);  /usr/include/lua5.1/lauxlib.h:LUALIB_API void (luaL_checkstack) (lua_State *L_ int sz_ const char *msg);  }}}    So these seem not to be existant in lua 5.2_ but in lua 5.1 only.    I will keep using lua 5.1 on Arch Linux for now.

**Comment by lkardos** [comment]
_Trac comment by JonnyJD on 2013-04-04 19:22:52:_

The patch is also sent to the ML:  http://lists.rpm.org/pipermail/rpm-maint/2013-April/003523.html    And is available on github:  https://github.com/JonnyJD/rpm/pull/1    The Arch package builds fine now:  https://aur.archlinux.org/packages/rpm-org/  (yes_ this should be named just "rpm"_ but that spot is somehow taken by rpm5)
